# Generated by Django 4.2.3 on 2023-08-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beboer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                ("tlf", models.BigIntegerField()),
                ("brugernavn", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("mail", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lattitude", models.DecimalField(decimal_places=6, max_digits=8)),
                ("longtitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Regler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regel", models.CharField(max_length=255)),
                ("beskrivelse", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Andmeldelse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "andmelder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HOAApi.beboer"
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HOAApi.location",
                    ),
                ),
                (
                    "regel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="HOAApi.regler"
                    ),
                ),
            ],
        ),
    ]
