# Generated by Django 4.2.3 on 2023-09-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOAApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="andmeldelse",
            name="location_id",
        ),
        migrations.AddField(
            model_name="andmeldelse",
            name="lattitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="andmeldelse",
            name="longtitude",
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
