# Generated by Django 4.2.3 on 2023-09-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "HOAApi",
            "0002_remove_andmeldelse_location_id_andmeldelse_lattitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="andmeldelse",
            name="lattitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
