# Generated by Django 4.2.3 on 2023-09-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOAApi", "0003_alter_andmeldelse_lattitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="andmeldelse",
            name="photo",
            field=models.ImageField(null=True, upload_to="media/images"),
        ),
    ]
