# Generated by Django 4.2.3 on 2023-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HOAApi", "0004_andmeldelse_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="andmeldelse",
            name="photo",
            field=models.ImageField(upload_to="media/images"),
        ),
    ]
